#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  RAG Chat — One-click VPS deploy script
#
#  Usage:
#    ./deploy.sh                        # interactive — prompts for values
#    DOCKER_IMAGE=myuser/rag-chat ./deploy.sh   # non-interactive
#
#  Requirements on the VPS:
#    - Docker + Docker Compose plugin (or standalone docker-compose)
#    - curl / wget
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

DEPLOY_DIR="${DEPLOY_DIR:-/opt/rag-chat}"
DOCKER_IMAGE="${DOCKER_IMAGE:-}"

# ── Helpers ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERR]${NC}  $*" >&2; exit 1; }

require() { command -v "$1" &>/dev/null || error "$1 is required but not installed."; }

# ── Pre-flight checks ─────────────────────────────────────────────────────────
require docker
require curl

# Detect compose command
if docker compose version &>/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose &>/dev/null; then
  COMPOSE="docker-compose"
else
  error "Docker Compose not found. Install it first: https://docs.docker.com/compose/install/"
fi
info "Using compose command: $COMPOSE"

# ── Interactive prompts ───────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}   RAG Chat — VPS Deployment Setup${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

if [[ -z "$DOCKER_IMAGE" ]]; then
  read -rp "Docker image (e.g. myuser/rag-chat or leave blank to build locally): " DOCKER_IMAGE
fi

read -rp "Deploy directory [${DEPLOY_DIR}]: " _dir
DEPLOY_DIR="${_dir:-$DEPLOY_DIR}"

read -rp "App port [3000]: " APP_PORT
APP_PORT="${APP_PORT:-3000}"

read -rp "Login username [admin]: " LOGIN_USERNAME
LOGIN_USERNAME="${LOGIN_USERNAME:-admin}"

read -rsp "Login password [admin123]: " LOGIN_PASSWORD
LOGIN_PASSWORD="${LOGIN_PASSWORD:-admin123}"
echo ""

read -rsp "Session secret (leave blank to auto-generate): " SESSION_SECRET
echo ""
if [[ -z "$SESSION_SECRET" ]]; then
  SESSION_SECRET="$(openssl rand -hex 32 2>/dev/null || cat /proc/sys/kernel/random/uuid | tr -d '-')"
  info "Auto-generated session secret."
fi

echo ""
echo "LLM provider options: anthropic | openai"
read -rp "LLM provider [anthropic]: " LLM_PROVIDER
LLM_PROVIDER="${LLM_PROVIDER:-anthropic}"

read -rp "LLM model [claude-sonnet-4-6]: " LLM_MODEL
LLM_MODEL="${LLM_MODEL:-claude-sonnet-4-6}"

read -rsp "LLM API key (can be set later in the app settings): " LLM_API_KEY
LLM_API_KEY="${LLM_API_KEY:-}"
echo ""

# ── Create deploy directory ───────────────────────────────────────────────────
info "Creating deploy directory: ${DEPLOY_DIR}"
mkdir -p "${DEPLOY_DIR}"

# ── Write .env ────────────────────────────────────────────────────────────────
info "Writing .env file…"
cat > "${DEPLOY_DIR}/.env" <<EOF
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
LOGIN_USERNAME=${LOGIN_USERNAME}
LOGIN_PASSWORD=${LOGIN_PASSWORD}
SESSION_SECRET=${SESSION_SECRET}
LLM_PROVIDER=${LLM_PROVIDER}
LLM_MODEL=${LLM_MODEL}
LLM_API_KEY=${LLM_API_KEY}
CHUNK_SIZE=512
CHUNK_OVERLAP=50
TOP_K=3
EOF
chmod 600 "${DEPLOY_DIR}/.env"
success ".env written (chmod 600)"

# ── Write docker-compose.yml ──────────────────────────────────────────────────
info "Writing docker-compose.yml…"

if [[ -n "$DOCKER_IMAGE" ]]; then
  # Pull from registry
  cat > "${DEPLOY_DIR}/docker-compose.yml" <<EOF
version: "3.9"

services:
  rag-chat:
    image: ${DOCKER_IMAGE}:latest
    container_name: rag-chat
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3000"
    env_file: .env
    environment:
      NODE_ENV: production
    volumes:
      - rag_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/categories"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  rag_data:
    driver: local
EOF
else
  # Build locally — clone the repo
  if [[ ! -d "${DEPLOY_DIR}/repo" ]]; then
    read -rp "Git repo URL (e.g. https://github.com/youruser/rag-chat): " GIT_REPO
    info "Cloning repo into ${DEPLOY_DIR}/repo…"
    git clone "$GIT_REPO" "${DEPLOY_DIR}/repo"
  fi
  cat > "${DEPLOY_DIR}/docker-compose.yml" <<EOF
version: "3.9"

services:
  rag-chat:
    build:
      context: ./repo
      dockerfile: Dockerfile
    container_name: rag-chat
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3000"
    env_file: .env
    environment:
      NODE_ENV: production
    volumes:
      - rag_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/categories"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  rag_data:
    driver: local
EOF
fi

success "docker-compose.yml written"

# ── Pull / build ──────────────────────────────────────────────────────────────
cd "${DEPLOY_DIR}"

if [[ -n "$DOCKER_IMAGE" ]]; then
  info "Pulling latest image: ${DOCKER_IMAGE}:latest …"
  docker pull "${DOCKER_IMAGE}:latest"
fi

# ── Start / restart ───────────────────────────────────────────────────────────
info "Starting RAG Chat…"
$COMPOSE down --remove-orphans 2>/dev/null || true
$COMPOSE up -d

# ── Health check ─────────────────────────────────────────────────────────────
echo ""
info "Waiting for app to become healthy (up to 60s)…"
for i in $(seq 1 12); do
  sleep 5
  if curl -sf "http://localhost:${APP_PORT}/api/categories" &>/dev/null; then
    echo ""
    success "RAG Chat is up and running!"
    echo ""
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}  URL      : http://<your-server-ip>:${APP_PORT}${NC}"
    echo -e "${GREEN}  Username : ${LOGIN_USERNAME}${NC}"
    echo -e "${GREEN}  Password : ${LOGIN_PASSWORD}${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    warn "Remember to set your LLM API key in Settings if you skipped it above."
    exit 0
  fi
  echo -n "."
done

echo ""
warn "App did not respond in time. Check logs with:"
echo "  cd ${DEPLOY_DIR} && $COMPOSE logs -f"
